Check slice thickness
deepc-health/nekton pull request #11
Opened 2021-12-09 18:20 UTC by a-parida12

Solves Issue & Closes #2 

This feature checks for variable slice thickness and rejects them

2021-12-09 19:28 UTC, yigitsoy commented on nekton/dcm2nii.py
> +from base import baseConverter
Consistent naming convention, e.g. UpperCamelCase for classes

2021-12-09 19:30 UTC, yigitsoy commented on nekton/dcm2nii.py
> +    def get_all_dicoms(self, dicom_directory: str) -> List[str]:
this could also be a static method I guess

2021-12-09 19:31 UTC, yigitsoy commented on nekton/dcm2nii.py
> +    def _run_conv_uniform(self, all_dcm_paths: List[str], name: str) -> str:
similarly here, if there is no need for using self, do not use it, but if you need to keep instance data, then, it makes sense.

2021-12-09 19:33 UTC, yigitsoy commented on nekton/dcm2nii.py
> +        return converted_file_path
I would add a general try/catch here in case subsequent calls fail

2021-12-09 19:33 UTC, yigitsoy commented on nekton/utils/json_helpers.py
> +        outfile.write(json_object)
to be correct, I would add a try/catch here too

2021-12-09 19:34 UTC, yigitsoy commented on nekton/utils/json_helpers.py
> +    return json_object
the same..

2021-12-09 19:38 UTC, yigitsoy requested changes
Please consider the points provided in the comments.

2021-12-09 20:58 UTC, a-parida12 commented on nekton/dcm2nii.py
> +    def _run_conv_uniform(self, all_dcm_paths: List[str], name: str) -> str:
This is part of another feature and will not be a static method, but left it for later

2021-12-10 12:23 UTC, yigitsoy approved these changes

2021-12-10 13:02 UTC, merged